import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/Sections/Navbar";
import Cursor from "@/app/Sections/Cursor";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Apple",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NavBar />
        <Cursor />
        {children}

      </body>
    </html>
  );
}
